title: Investor Relations
description: The investor relations website of the Jack's Dogs Family company.
theme: just-the-docs

url: https://investors.jacksdogsfamily.tk

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
